version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=tarefa
      - POSTGRES_PASSWORD=tarefa
      - POSTGRES_DB=tarefa
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "leoo.caldas@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "81:8080"
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  app:
    image: golang:1.19-alpine
    build: ./ToDoListAPI-go-postgres
    container_name: api-backend
    command: [ "go", "run", "main.go" ]
    ports:
      - 5050:5050
    depends_on:
      - postgres
      - pgadmin-compose
    working_dir: /ToDoListAPI-go-postgres
    volumes:
      - ./:/ToDoListAPI-go-postgres
    restart: on-failure
