openapi: 3.0.3
info:
  title: To do list API
  description: Essa é uma API que serve como o back-end de uma lista de tarefas.
  version: 0.0.1
  contact:
    name: email
    email: leoo.caldas@hotmail.com  
servers:
- url: http://localhost:5050
  description: API 
paths:
  /api/tarefas:
    get:
      summary: Exibe todas as tarefas.
      responses:
        200:
          description: Sucesso
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    filtro:
                      type: string
                    pronto:
                      type: boolean
    post:
     summary: Cria uma nova tarefa.
     requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                filtro:
                  type: string
                pronto:
                  type: boolean
             
     responses:
      201:
        description: Sucesso
        content: 
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                filtro:
                  type: string
                pronto:
                  type: boolean
  /api/tarefas/{id}:
    parameters:
    - name: id
      in: path
      schema:
       type: integer
      required: true
    get:
        summary: Exibe uma tarefa pelo ID.
        responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      nome:
                        type: string
                      filtro:
                        type: string
                      pronto:
                        type: boolean
          404:
            description: Tarefa não encontrada
            content:
              application/json:
                example: "Não encontrado"
    put:
      summary: Edita uma tarefa.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                filtro:
                  type: string
                pronto:
                  type: boolean
      responses:
       201:
        description: Sucesso
        content: 
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                filtro:
                  type: string
                pronto:
                  type: boolean
    delete:
      summary: Deleta uma tarefa.
      responses:
       201:
        description: Sucesso
        content: 
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                filtro:
                  type: string
                pronto:
                  type: boolean
      
  /api/tarefas/tarefa:
    parameters:
      - name: filtro
        in: query
        schema:
          type: string
        required: true
    post:
      summary: Exibe uma tarefa pela query.
      responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      nome:
                        type: string
                      filtro:
                        type: string
                      pronto:
                        type: boolean
          404:
            description: Tarefa não encontrada
            content:
              application/json:
                example: "Não encontrado"
        
    
      

  